import { chromium } from "playwright";
const browser = await chromium.launch();
const p = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await p.goto("http://127.0.0.1:5199/#calendar", { waitUntil: "load" });
await p.waitForTimeout(1000);
const avail = p.locator("button[aria-label$=', available']").first();
console.log("aria:", await avail.getAttribute("aria-label"));
const pre = await avail.evaluate((el) => getComputedStyle(el).filter);
await avail.hover();
await p.waitForTimeout(250);
const post = await avail.evaluate((el) => getComputedStyle(el).filter);
console.log(JSON.stringify({ pre, post }));
await browser.close();
